export const CART_ITEMS_FETCHED_SUCCESSFULLY = 'CART_ITEMS_FETCHED_SUCCESSFULLY';
export const CART_ITEMS_FETCH_FAILED = 'CART_ITEMS_FETCH_FAILED';
export const QUANTITY_CHANGED = 'QUANTITY_CHANGED';
export const ITEM_DELETED = 'ITEM_DELETED';